fix: [statusWithText] исправление внешнего вида согласно макету
JuicyInno/JuicyFront pull request #129
Opened 2021-11-16 11:05 UTC by AnnaDanshina

2021-11-16 16:01 UTC, feerzlay requested changes

2021-11-16 16:01 UTC, feerzlay commented on src/index.ts
> -import Status from './components/atoms/Status';
А вот интересно, на сервисах этот компонент не используется случайно? А то как упадет сборка после обновления =)

2021-11-16 20:01 UTC, AnnaDanshina commented on src/assets/icons/24px/Status/ReleaseSecondary.tsx
> +        fill='#0D69F2'
Эта иконка относится к группе иконок-статусов, цвета у которых фиксированы, макет здесь https://www.figma.com/file/Tl0AmqQJK4qaCl4pLRio7A/Design-System-for-Story-Book?node-id=1238%3A24148

2021-11-16 20:04 UTC, AnnaDanshina commented on src/components/atoms/StatusWithText/StatusWithText.tsx
> +    criticality: string;
Компонент является частью истории, проп criticality зафиксирован с бэка, идёт прямиком куском данных, была договорённость использовать именно эти значения - цифры в строке.

2021-11-16 20:05 UTC, AnnaDanshina commented on src/index.ts
> -import Status from './components/atoms/Status';
Этот компонент является частью только истории, больше он нигде не используется.

2021-11-17 14:53 UTC, AnnaDanshina commented on src/components/atoms/StatusWithText/StatusWithText.spec.tsx
> +        expect(container.getElementsByClassName('rf-status-with-text__success')).toHaveLength(1);
Спасибо, буду иметь в виду.

2021-11-18 08:29 UTC, feerzlay approved these changes

2021-11-18 08:31 UTC, merged