Badge fixing
JuicyInno/JuicyFront pull request #155
Opened 2021-11-23 12:20 UTC by AlexanderRusakus

2021-11-24 13:44 UTC, KudelAndrei commented on src/components/atoms/Badge/Badge.tsx
> +  size?: 'S' | 'M';
замени плиз на меленькие `s m`

2021-11-24 14:03 UTC, KudelAndrei approved these changes

2021-11-25 07:35 UTC, feerzlay requested changes

2021-11-25 07:35 UTC, feerzlay commented on src/components/atoms/Badge/Badge.scss
> +  background-color: #fff;
Не background-primary должно быть?

2021-11-25 08:08 UTC, feerzlay approved these changes

2021-11-25 08:17 UTC, merged