Timepicker update
JuicyInno/JuicyFront pull request #238
Opened 2021-12-21 13:24 UTC by AlexanderRusakus

2022-01-14 09:25 UTC, dangurova commented on src/components/atoms/Input/Input.scss
> +  box-shadow: none !important;
без !important нельзя обойтись?

2022-01-14 09:25 UTC, dangurova commented on src/components/atoms/Input/Input.scss
> +  box-shadow: none !important;
может лучше увеличить вес селекторов

2022-01-14 09:25 UTC, dangurova commented on src/components/atoms/Timepicker/Timepicker.spec.tsx
> +      expect(document.getElementsByClassName('rf-time-element__wrapper').length).toBe(0)
точно работает и нужен ли waitFor (то что вчера обсуждали)?

2022-01-14 09:25 UTC, dangurova commented on src/components/molecules/ButtonGroup/mock.tsx
> +      /*       console.log('Подбор'); */
думаю нужно вернуть, либо если оно изменилось и выполняется еще где-то, то оставить пустые {}

2022-01-14 09:25 UTC, dangurova commented on src/components/molecules/ButtonGroup/mock.tsx
> +      /*     console.log('Подбор'); */
думаю нужно вернуть, либо если оно изменилось и выполняется еще где-то, то оставить пустые {}

2022-01-14 09:25 UTC, dangurova commented on src/components/popups/FindEntities/FindEntities.tsx
> +    /*  console.log(entity); */
они нужны?

2022-01-14 09:25 UTC, dangurova commented on src/components/popups/FindEntities/FindEntities.tsx
> +      /*  console.log('Checked'); */
они нужны?

2022-01-14 11:47 UTC, AlexanderRusakus commented on src/components/atoms/Input/Input.scss
> +  box-shadow: none !important;
обойтись

2022-01-14 11:51 UTC, AlexanderRusakus commented on src/components/atoms/Timepicker/Timepicker.spec.tsx
> +      expect(document.getElementsByClassName('rf-time-element__wrapper').length).toBe(0)
убрал, работает

2022-01-14 11:54 UTC, AlexanderRusakus commented on src/components/molecules/ButtonGroup/mock.tsx
> +      /*       console.log('Подбор'); */
Вернул

2022-01-25 09:03 UTC, feerzlay requested changes

2022-01-25 09:03 UTC, feerzlay commented on src/components/atoms/Input/Input.tsx
> +  /** Добавить рамку */
Добавить тут что `@default true`

2022-01-25 13:55 UTC, feerzlay approved these changes

2022-01-25 13:56 UTC, merged