[rav] add endAdornment to hcf
JuicyInno/JuicyFront pull request #248
Opened 2022-01-03 09:15 UTC by AlexanderRusakus

2022-01-21 13:53 UTC, KudelAndrei commented on src/assets/icons/Cross.tsx
> +    <path fillRule='evenodd' clip-rule='evenodd' d='M18.7071 5.29289C19.0976 5.68342 19.0976 6.31658 18.7071 6.70711L6.70711 18.7071C6.31658 19.0976 5.68342 19.0976 5.29289 18.7071C4.90237 18.3166 4.
clipRule

2022-01-21 13:53 UTC, KudelAndrei commented on src/assets/icons/Cross.tsx
> +    <path fillRule='evenodd' clip-rule='evenodd' d='M18.7071 5.29289C19.0976 5.68342 19.0976 6.31658 18.7071 6.70711L6.70711 18.7071C6.31658 19.0976 5.68342 19.0976 5.29289 18.7071C4.90237 18.3166 4.
fill= currentColor

2022-01-21 13:53 UTC, KudelAndrei commented on src/components/atoms/Datepicker/Datepicker.tsx
> +                            <Cross style={{ color: '#8A96A8' }} onClick={clearDateRangeHandler} /> :
цвет через родителя стили можно задавать

2022-01-21 13:53 UTC, KudelAndrei commented on src/components/atoms/Select/Select.scss
> +  box-shadow: none;
а почему ты бордер убрал у селекта ?

2022-01-21 13:53 UTC, KudelAndrei commented on src/styles/index.scss
> +  height: 100vh;
это зачем ?

2022-01-24 07:43 UTC, AlexanderRusakus commented on src/components/atoms/Select/Select.scss
> +  box-shadow: none;
Вернул, оставил локально у кард филтера

2022-01-24 07:44 UTC, AlexanderRusakus commented on src/styles/index.scss
> +  height: 100vh;
убрал

2022-01-25 09:12 UTC, feerzlay requested changes

2022-01-25 09:12 UTC, feerzlay commented on src/components/atoms/Search/Search.tsx
> +  /**  */
Добавить описание?

2022-01-25 09:12 UTC, feerzlay commented on src/components/molecules/HistoryCardFilter/HistoryCardFilter.stories.tsx
> +const buttonComponent = <Button buttonType='primary' onClick={() => {
Не используется?

2022-01-25 09:12 UTC, feerzlay commented on src/components/molecules/HistoryCardFilter/HistoryCardFilter.spec.tsx
> +import { Button } from '../../..';
Не используется?

2022-01-25 09:12 UTC, feerzlay commented on src/components/atoms/Datepicker/Datepicker.tsx
> +   *  Сыылка на контейнер портала
Что-то не то с описанием

2022-01-25 09:12 UTC, feerzlay commented on src/assets/icons/Cross.tsx
> +  <svg width='24' height='24' viewBox='0 0 24 24' fill='currentColor' xmlns='http://www.w3.org/2000/svg' {...props}>
Это ничего никому не сломает, что размер иконки поменялся?

2022-01-25 10:45 UTC, AlexanderRusakus commented on src/components/molecules/HistoryCardFilter/HistoryCardFilter.stories.tsx
> +const buttonComponent = <Button buttonType='primary' onClick={() => {
нет

2022-01-25 10:46 UTC, AlexanderRusakus commented on src/components/atoms/Datepicker/Datepicker.tsx
> +   *  Сыылка на контейнер портала
поправил

2022-01-25 11:00 UTC, AlexanderRusakus commented on src/assets/icons/Cross.tsx
> +  <svg width='24' height='24' viewBox='0 0 24 24' fill='currentColor' xmlns='http://www.w3.org/2000/svg' {...props}>
У всех иконок уже 24

2022-01-25 13:54 UTC, feerzlay approved these changes

2022-01-25 13:56 UTC, merged