refactor: [AD] avatarStatus + Badge refactoring
JuicyInno/JuicyFront pull request #29
Opened 2021-10-15 15:16 UTC by AnnaDanshina

2021-10-20 05:37 UTC, Michaeladze commented on src/styles/mixins.scss
> +@mixin elemSize($r) {
Не самое говорящее название. Я бы назвал square()

2021-10-20 05:59 UTC, Michaeladze commented on src/components/atoms/AvatarStatus/AvatarStatus.tsx
> +    case 'yellow': icon = <Redo className='rf-avatar-status__icon-style' />;
Проверь иконоки, они почему-то не по центру круга. Возможно, то-то с самой иконкой из фигмы и нуно будет у дизайнеров попросить другую иконку

2021-10-20 06:00 UTC, Michaeladze requested changes
Оставил комментарии по коду

2021-11-16 05:00 UTC, JuicyInno approved these changes

2021-11-25 13:02 UTC, closed without merging